# Generated by Django 4.2.9 on 2024-02-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='is_autofilled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='domain',
            name='creation_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='domain',
            name='registrar',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='domain',
            name='registry_expiry_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='updated_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
