# Generated by Django 4.2.9 on 2024-02-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0002_domain_is_autofilled_alter_domain_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='creation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='registry_expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
