# Generated by Django 4.2.9 on 2024-02-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0003_alter_domain_creation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='is_autofilled',
        ),
        migrations.AddField(
            model_name='domain',
            name='last_whois_lookup',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
