# Generated by Django 4.2.9 on 2024-03-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0004_remove_domain_is_autofilled_domain_last_whois_lookup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='registrar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
